### PR TITLE
Update meta.yaml from upstream build dependencies

### PR DESCRIPTION
**Pull request by achimgaedke**
fixing up build pipeline reflecting build dependency changes for upstream version 2

there are also some runtime dependency changes, but first focussing on repairing build...

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Reset the build number to `0` (if the version changed)

### CODE REVIEW

**Comment by achimgaedke** [comment]
Hmmm, looks like I'm not understanding what's going on here.... Will need to read up a bit more / use docker for debugging locally.

**Comment by felixgwilliams** [comment]
Thanks for having a look at this.  It looks like if the requirements part is changed to the following, it seems to be successful:

```yaml
requirements:
  host:
    - hatchling >=1.4.0
    - hatch-nodejs-version
    - hatch-jupyter-builder>=0.5
    - python >=3.7
    - pip
  run:
    - jupyter_server >=1.21,<3
    - python >=3.7

```

**Comment by achimgaedke** [comment]
Thanks, @felixgwilliams - I also started understanding that I confuse `host`and `build`... too many "isolated virtual" environments.

**Comment by achimgaedke** [comment]
Ok, https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#host is clear about this: architecture-independent packages use `host`.

I've used @felixgwilliams suggestions - and will ready this PR for review.

**Review by dbast — APPROVED** [review]

**Pull request merged**
